version: '3'

services:
  app:
    image: meaty/lawncareapi
    build: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/lawncare?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_REDIS_HOST=redis-cache
    ports:
      - 8080
    restart: always
    depends_on:
      - db
      - nginx
      - rabbitmq

  db:
    image: mysql:latest
    restart: always
    container_name: db
    environment:
      - MYSQL_DATABASE=lawncare
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 4000:3306
    volumes:
      - lawncaredata:/var/lib/mysql:rw
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 5000:5000
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
  redis-cache:
    image: redis:alpine
    volumes:
      - rediscache:/var/lib/redis:rw
    ports:
      - 6379:6379
  consumer:
    image: meaty/consumer
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
    ports:
      - 8081
    restart: always
    depends_on:
      - rabbitmq
      - app


volumes:
  rediscache:
  lawncaredata:
