version: '3'

services:
  app:
    image: meaty/lawncareapi
    build: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/lawncare?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
    ports:
      - 8080
    restart: always
    depends_on:
      - db
      - nginx

  db:
    image: mysql:latest
    restart: always
    container_name: db
    environment:
      - MYSQL_DATABASE=lawncare
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 4000:3306
    volumes:
      - lawncaredata:/var/lib/mysql:rw
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 5000:5000
#  rabbitmq:
#    image: rabbitmq:3-management
#    ports:
#      - 5672:5672
#      - 15672:15672


volumes:
  lawncaredata:
